#ifndef HEADER_ERROR
#define HEADER_ERROR

/**
 * this defines all possible errors
 */
typedef enum {
    ERROR_NULL,
    ERROR_LEXIC,
    ERROR_SYNTAX,
    ERROR_SYNTAX_PROPAGATING,
    ERROR_PREPROCESSING,
    ERROR_ALLOCATION_FAILED,
    ERROR_UNEXPECTED_EOF,
    ERROR_MISSING_CLOSE_PARENTHESES,
    ERROR_UNKNOWN_SUFFIX_OP,
    ERROR_EXPECTED_NUMBER_ID,
} Error;

#endif